import { AuthContextProvider } from '@/context/auth'
import { BucketContextProvider } from '@/context/bucket'
import PageLayout from '@/layout'
import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Allnutrition Catering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <AuthContextProvider>
        <BucketContextProvider>
          <PageLayout>

            <Component {...pageProps} />
          </PageLayout>
        </BucketContextProvider>
      </AuthContextProvider>
    </>


  )
}
